eligible_words = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
'about', 'above', 'across', 'actress', 'address', 'aeroplane', 'after', 'again', 'alive', 'allergy', 'aluminium', 'always', 'apple', 
'area', 'around', 'assembly', 'baby', 'badminton', 'ball', 'bandh', 'basketball', 'bat', 'before', 'behind', 'bell', 'below', 'bengali', 
'between', 'birth', 'bloodpressure', 'boat', 'bogie', 'boxing', 'boy', 'brass', 'brother', 'cancer', 'capital', 'carrom', 'cement', 
'centimeter', 'chess', 'cholera', 'christmas', 'coal', 'coconut', 'cold', 'corn', 'cough', 'cremate', 'cure', 'diabetes', 'die', 
'disease', 'down', 'durga', 'during', 'election', 'engine', 'exercise', 'far', 'flag', 'foot', 'friend', 'from', 'fruit', 'funeral', 
'game', 'ghost', 'government', 'grain', 'gram', 'grandfather', 'grandmother', 'grandson', 'groundut', 'guard', 'gujarati', 'health', 
'helicopter', 'here', 'hindi', 'history', 'hockey', 'holi', 'housefly', 'inch', 'jackfruit', 'jaundice', 'karate', 'kilogram', 
'kilometer', 'king', 'kite', 'leader', 'leather', 'lemon', 'leprosy', 'lighthouse', 'litre', 'lose', 'magnet', 'malayalam', 'marathi', 
'mary', 'measles', 'measure', 'measurement', 'meter', 'mile', 'mililitre', 'minister', 'mug', 'mumbs', 'mumps', 'near', 'neighbour', 
'newspaper', 'olympics', 'out', 'over', 'parliament', 'plastic', 'poison', 'pomegranate', 'postman', 'power', 'pray', 'president', 
'priest', 'queen', 'race', 'railway', 'relative', 'reservation', 'rice', 'riots', 'rocket', 'room', 'rubber', 'run', 'scale', 'seat', 
'ship', 'sick', 'silk', 'silver', 'sometime', 'son', 'steel', 'strike', 'surname', 'tamil', 'telgu', 'temperature', 'there', 'through', 
'ticket', 'toilet', 'towards', 'trophy', 'twin', 'under', 'urdu', 'vote', 'wedding', 'weight', 'wheat', 'wife', 'win', 'with', 
'without', 'woman', 'wood', 'wool', 'wound']